P1_SW1 = "GPIO10"
P1_SW2 = "GPIO13"
P1_SW3 = "GPIO11"
P1_SW4 = ""
P1_SW5 = "GPIO12"
P1_SW6 = "GPIO7"
P1_SW7 = "GPIO8"

# P2_SW1 = "GPIO13"
# P2_SW2 = "GPIO10"
# P2_SW3 = "GPIO9"
# P2_SW4 = "GPIO9"
# P2_SW5 = "GPIO7"
# P2_SW6 = "GPIO12"
# P2_SW7 = "GPIO11"
